In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
from sklearn.preprocessing import MinMaxScaler

In [5]:
data = [[17, 62], [83, 24], [49, 90], [31, 76]]
data = pd.DataFrame(data)
data

0   1
0  17  62
1  83  24
2  49  90
3  31  76

接下来开始实现归一化

In [7]:
scaler = MinMaxScaler()
scaler =scaler.fit(data) #如果数据量太大了就用partial_fit
result = scaler.transform(data)
result = pd.DataFrame(result)
result

0         1
0  0.000000  0.575758
1  1.000000  0.000000
2  0.484848  1.000000
3  0.212121  0.787879

也可以一步到位

In [8]:
result2 = scaler.fit_transform(data)
result2

array([[0.        , 0.57575758],
       [1.        , 0.        ],
       [0.48484848, 1.        ],
       [0.21212121, 0.78787879]])

可以逆转归一化的结果

In [9]:
scaler.inverse_transform(result2)

array([[17., 62.],
       [83., 24.],
       [49., 90.],
       [31., 76.]])

将归一化的结果换一个区间

In [13]:
scaler2 = MinMaxScaler(feature_range=(5,10))
result3 = scaler2.fit_transform(data)
result3

array([[ 5.        ,  7.87878788],
       [10.        ,  5.        ],
       [ 7.42424242, 10.        ],
       [ 6.06060606,  8.93939394]])